-- Baseline: captures the log_source table as it already exists in any
-- pre-Flyway database (created by Hibernate's ddl-auto=update). On an
-- existing database, spring.flyway.baseline-on-migrate marks this version as
-- already applied without running it. On a brand-new database, this creates
-- the table from scratch, since there's nothing to baseline against.
CREATE TABLE log_source (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    type            VARCHAR(255) NOT NULL,
    path            VARCHAR(255),
    host            VARCHAR(255),
    port            INTEGER,
    username        VARCHAR(255),
    password        VARCHAR(255),
    status          VARCHAR(255) NOT NULL,
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    live            BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP NOT NULL,
    last_checked_at TIMESTAMP
);
