-- Saved Searches: a bookmark of either the plain-filter UI (queryLanguage
-- SIMPLE, using search/levels) or a query-bar string (LUCENE/SPL/LOGQL,
-- using query) plus shared source/file/range/sort scoping. One flat table,
-- no per-language side tables, mirroring log_source's own shape.
CREATE TABLE saved_search (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    query_language VARCHAR(255) NOT NULL,
    query          VARCHAR(2000),
    search         VARCHAR(2000),
    levels         VARCHAR(255),
    source         VARCHAR(255),
    file           VARCHAR(255),
    range_minutes  BIGINT NOT NULL DEFAULT 0,
    sort_by        VARCHAR(255) NOT NULL DEFAULT 'time',
    sort_dir       VARCHAR(255) NOT NULL DEFAULT 'desc',
    created_at     TIMESTAMP NOT NULL
);
