-- Alert rules: a watch rule over a subset of indexed logs. Scope columns
-- mirror saved_search's shape exactly (a deliberate copy, not a foreign key -
-- deleting a saved search must never silently break an alert). THRESHOLD
-- rules use comparison_op/threshold; ANOMALY rules use the anomaly_* columns.
CREATE TABLE alert_rule (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                      VARCHAR(255) NOT NULL,
    query_language            VARCHAR(255) NOT NULL,
    query                     VARCHAR(2000),
    search                    VARCHAR(2000),
    levels                    VARCHAR(255),
    source                    VARCHAR(255),
    file                      VARCHAR(255),
    rule_type                 VARCHAR(255) NOT NULL,
    window_minutes            INTEGER NOT NULL,
    metric                    VARCHAR(255) NOT NULL,
    comparison_op             VARCHAR(255),
    threshold                 DOUBLE,
    anomaly_baseline_windows  INTEGER,
    anomaly_std_dev_multiplier DOUBLE,
    muted                     BOOLEAN NOT NULL DEFAULT FALSE,
    last_triggered_at         TIMESTAMP,
    last_evaluated_at         TIMESTAMP,
    webhook_url               VARCHAR(2000),
    webhook_secret            VARCHAR(500),
    created_at                TIMESTAMP NOT NULL
);

-- Trigger history: one row per trigger-to-resolve span, gives
-- last_triggered_at a real audit trail instead of a single overwritable
-- field. No FK constraint, matching this schema's informal-reference style.
CREATE TABLE alert_event (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_rule_id        BIGINT NOT NULL,
    triggered_at         TIMESTAMP NOT NULL,
    resolved_at          TIMESTAMP,
    metric_value         DOUBLE NOT NULL,
    threshold_at_trigger DOUBLE,
    webhook_status       INTEGER
);
