-- Regex-based redaction/masking rules applied to log message content at
-- ingest time. source is a name copy (nullable = applies globally), matching
-- alert_rule's informal-reference scoping style rather than a foreign key.
CREATE TABLE redaction_rule (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    pattern      VARCHAR(1000) NOT NULL,
    replacement  VARCHAR(255),
    source       VARCHAR(255),
    enabled      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP NOT NULL
);
