-- Clustered log message "shapes" mined incrementally per source (LOGIC-107).
-- source is a name copy, always scoped (no global bucket - a template tree
-- is inherently per-source, unlike redaction_rule's optional global scope).
-- history is a comma-separated ring of recent per-minute occurrence counts
-- backing the Patterns UI's trend sparkline.
CREATE TABLE log_template (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source                       VARCHAR(255) NOT NULL,
    template_text                VARCHAR(2000) NOT NULL,
    token_count                  INT NOT NULL,
    occurrence_count             BIGINT NOT NULL,
    first_seen_at                TIMESTAMP NOT NULL,
    last_seen_at                 TIMESTAMP NOT NULL,
    sample_raw_line              VARCHAR(2000),
    history                      VARCHAR(500),
    history_bucket_start_millis  BIGINT
);

CREATE INDEX idx_log_template_source ON log_template(source);
CREATE INDEX idx_log_template_last_seen_at ON log_template(last_seen_at);
