-- LOGIC-110: append-only admin action audit trail. Every create/update/delete
-- on LogSource, AlertRule, and RedactionRule writes one row here; old_value/
-- new_value are JSON snapshots of the entity's non-secret fields (passwords/
-- webhook secrets are never included). No FK constraints, matching this
-- schema's informal-reference style (see alert_event/redaction_rule) - and
-- deliberately no update/delete path from the service layer, so the table
-- stays append-only from the API's point of view.
CREATE TABLE audit_log_entry (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(255) NOT NULL,
    entity_id   BIGINT NOT NULL,
    entity_name VARCHAR(255) NOT NULL,
    action      VARCHAR(255) NOT NULL,
    actor       VARCHAR(255) NOT NULL,
    old_value   VARCHAR(4000),
    new_value   VARCHAR(4000),
    timestamp   TIMESTAMP NOT NULL
);

CREATE INDEX idx_audit_log_entry_timestamp ON audit_log_entry (timestamp);
